In [2]:
import numpy as np
array1 = np.array([[1,2,3],[4,5,6]])

In [3]:
np.shape(array1)

(2, 3)

In [6]:
array2 = np.ones(5)
print(array2)

[1. 1. 1. 1. 1.]


In [8]:
array3 = np.ones((2,3))
print(array3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
lista = [[1,2,3],[4,5,6],[7,8,9]]
array4 = np.matrix(lista)

In [10]:
print(array4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
np.shape(array4)

(3, 3)

In [12]:
array4.size

9

In [13]:
array4[2,1]

8