In [1]:
import numpy as np

BASIC

In [2]:
np.array([1,23,4,5,6])

array([ 1, 23,  4,  5,  6])

In [3]:
a = np.array([2,1,3,4,5])

In [4]:
b = np.array([1.,2.,3.])

In [5]:
a[0]

2

In [6]:
a[0],a[1]

(2, 1)

In [7]:
a[0:3]

array([2, 1, 3])

In [9]:
b[[0,2]]

array([1., 3.])

Array types

In [11]:
a.dtype

dtype('int32')

In [12]:
b.dtype

dtype('float64')

In [16]:
# Selecting array type manually
c = np.array([1,2,3,4,5], dtype=np.float64)
c

array([1., 2., 3., 4., 5.])

DIMENSIONS AND SHAPES

In [17]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [18]:
A.shape

(2, 3)

In [19]:
A.ndim

2

In [20]:
A.size

6

In [22]:
B = np.array([
    [
        [12,33,35],
        [8,9,40]
    ],
    [
        [56,44,86],
        [84,65,11]
    ]
])

In [23]:
B.shape

(2, 2, 3)

In [24]:
B.size

12

INDEX AND SLICING MATRIX

In [25]:
A[1]

array([4, 5, 6])

In [26]:
A[1][0]

4

In [27]:
A[1,0]

4

In [29]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
A[:,1]

array([2, 5])

In [36]:
A[1,:1]

array([4])

In [33]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
A[1] = np.array([10,10,10])

In [38]:
A

array([[ 1,  2,  3],
       [10, 10, 10]])

In [39]:
A[0,2] = 99

In [40]:
A

array([[ 1,  2, 99],
       [10, 10, 10]])

STATISTICS

In [41]:
d = np.array([1,2,3,4,5,6])
d.sum()

21

In [42]:
d.mean()

3.5

In [43]:
d.std()

1.707825127659933

In [45]:
f = np.array([
    [10,2,3],
    [4,5,6]
])

f.sum()

30

In [46]:
f.sum(axis=0)

array([14,  7,  9])

In [47]:
f.sum(axis=1)

array([15, 15])

BROADCASTING AND VECTORIZED OPERATIONS

In [48]:
g = np.arange(4)

In [49]:
g

array([0, 1, 2, 3])

In [50]:
g + 10

array([10, 11, 12, 13])

In [51]:
g * 10

array([ 0, 10, 20, 30])

In [52]:
g

array([0, 1, 2, 3])

BOOLEAN ARRAYS

In [53]:
a1 = np.arange(5)

In [63]:
a1 >= 2

array([False, False,  True,  True,  True])

In [64]:
a1[[True, False,  True,  True,  True]]

array([0, 2, 3, 4])

In [65]:
a1[a1>=2]

array([2, 3, 4])

In [58]:
a1[(a1 == 1) | (a1 == 4)]

array([1, 4])

In [59]:
a1[(a1 >= 1) & (a1 < 4)]

array([1, 2, 3])

Useful numpy functions


RANDOM

In [3]:
np.random.randint( 10, size=(10))

array([6, 1, 2, 0, 2, 8, 4, 2, 6, 9])

In [4]:
np.random.normal(size=2)

array([0.45002225, 1.64033862])

In [15]:
np.random.rand(2,3)

array([[0.39008623, 0.52877685, 0.61144892],
       [0.43392546, 0.12587741, 0.95949148]])

ARANGE

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [18]:
np.arange(0,1,.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

RESHAPE

In [19]:
np.arange(10).reshape(2,5)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

LINSPACE

In [21]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [22]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [24]:
np.linspace(0,1,10,True)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [25]:
np.linspace(0,1,10,False)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

ZEROS / ONES / EMPTY

In [26]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [27]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.ones(4)

array([1., 1., 1., 1.])

In [30]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
np.empty(3)

array([0.37092512, 0.42271598, 0.80638469])

In [36]:
np.empty((2, 2))

array([[1., 1.],
       [1., 1.]])

identity and eye

In [33]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])